/*
 * generated by Xtext 2.22.0
 */
package seproj.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import seproj.CalRuntimeModule;
import seproj.CalStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CalIdeSetup extends CalStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CalRuntimeModule(), new CalIdeModule()));
	}
	
}
