/*
 * generated by Xtext 2.22.0
 */
package seproj;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CalStandaloneSetup extends CalStandaloneSetupGenerated {

	public static void doSetup() {
		new CalStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
