<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sEProj" nsURI="http://www.example.org/sEProj" nsPrefix="sEProj">
  <eClassifiers xsi:type="ecore:EClass" name="VCalendar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calscale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prodid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="Software-Eng.projet" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="2.0" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VEvent" eSuperTypes="#//TemporalComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtend" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Date">
    <eOperations name="toString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freq" eType="#//FreqEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryDayNumber" upperBound="-1"
        eType="#//EntryDAYNumber" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FreqEnum">
    <eLiterals name="WEEKLY"/>
    <eLiterals name="MONTHLY" value="1"/>
    <eLiterals name="DAILY" value="2" literal="DAILY"/>
    <eLiterals name="YEARLY" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalComponent" abstract="true" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtstamp" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtstart" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="last_modified" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="created" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rrule" eType="#//RRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//StatusEnum"
        defaultValueLiteral="UNDEFINED"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exdate" upperBound="-1"
        eType="#//Date" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTODO" eSuperTypes="#//TemporalComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="due" eType="#//Date" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatusEnum">
    <eLiterals name="TENTATIVE"/>
    <eLiterals name="CONFIRMED" value="1"/>
    <eLiterals name="CANCELLED" value="2"/>
    <eLiterals name="NEEDSACTION" value="3" literal="NEEDS-ACTION"/>
    <eLiterals name="COMPLETED" value="4"/>
    <eLiterals name="INPROCESS" value="5" literal="IN-PROCESS"/>
    <eLiterals name="DRAFT" value="6"/>
    <eLiterals name="FINAL" value="7"/>
    <eLiterals name="UNDEFINED" value="8" literal="UNDEFINED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VJournal" eSuperTypes="#//TemporalComponent"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DAY">
    <eLiterals name="MONDAY" literal="MO"/>
    <eLiterals name="TUESDAY" value="1" literal="TU"/>
    <eLiterals name="WEDNESDAY" value="1" literal="WE"/>
    <eLiterals name="THURSDAY" value="1" literal="TH"/>
    <eLiterals name="FRIDAY" value="1" literal="FR"/>
    <eLiterals name="SATURDAY" value="1" literal="SA"/>
    <eLiterals name="SUNDAY" value="1" literal="SU"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntryDAYNumber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byDay" eType="#//DAY" defaultValueLiteral="MO"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byDayNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTimeZone" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TZID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastMod" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TZURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
