<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sEProj" nsURI="http://www.example.org/sEProj" nsPrefix="sEProj">
  <eClassifiers xsi:type="ecore:EClass" name="VCalendar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calscale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prodid" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="&quot;Software-Eng.projet&quot;" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        defaultValueLiteral="2.0" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VEvent" eSuperTypes="#//TemporalComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtend" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Date">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freq" eType="#//FreqEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FreqEnum">
    <eLiterals name="WEEKLY"/>
    <eLiterals name="MONTHLY" value="1"/>
    <eLiterals name="DAILY" value="2" literal="DAILY"/>
    <eLiterals name="YEARLY" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalComponent" abstract="true" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtstamp" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtstart" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="last_modified" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="created" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rrule" eType="#//RRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//StatusEnum"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTODO" eSuperTypes="#//TemporalComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="due" eType="#//Date" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatusEnum">
    <eLiterals name="TENTATIVE"/>
    <eLiterals name="CONFIRMED" value="1"/>
    <eLiterals name="CANCELLED" value="2"/>
    <eLiterals name="NEEDSACTION" value="3" literal="NEEDS-ACTION"/>
    <eLiterals name="COMPLETED" value="4"/>
    <eLiterals name="INPROCESS" value="5" literal="IN-PROCESS"/>
    <eLiterals name="DRAFT" value="6"/>
    <eLiterals name="FINAL" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VJournal" eSuperTypes="#//TemporalComponent"/>
</ecore:EPackage>
