/*
 * generated by Xtext 2.22.0
 */
package seproj.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CalUiModule extends AbstractCalUiModule {

	public CalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
